# Generated by Django 3.0.7 on 2020-12-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='fname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
