# Generated by Django 2.0.8 on 2020-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201201_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='menu_id',
        ),
        migrations.AddField(
            model_name='item',
            name='menu_id',
            field=models.IntegerField(default=0),
        ),
    ]
