# Generated by Django 2.0.8 on 2020-12-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201206_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fname',
            new_name='items',
        ),
    ]
