# Generated by Django 2.0.8 on 2020-12-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201208_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu_id',
        ),
    ]
