# Generated by Django 2.0.8 on 2020-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201209_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfield',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='item',
            name='menu_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AddField',
        ),
    ]
